import os
import re

BASE = r"c:\Users\User\Desktop\Freelancing\WorkHoliday\countries"

# Embassy data: key = (origin, destination)
# Values: (name, address, phone, website, note)
EMBASSIES = {
    # Australia as destination
    ("Argentina", "Australia"): ("Australian Embassy, Buenos Aires", "Villanueva 1400, C1426BMJ Buenos Aires, Argentina", "+54 11 4779 3500", "argentina.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The embassy handles consular matters; visa applications are submitted online."),
    ("Austria", "Australia"): ("Australian Embassy, Vienna", "Gertrude-Froehlich-Sandner-Str. 2, 1100 Vienna, Austria", "+43 1 506 740", "austria.embassy.gov.au", "Visa applications are submitted online at immi.homeaffairs.gov.au. Contact the embassy for consular assistance."),
    ("Belgium", "Australia"): ("Australian Embassy, Brussels", "Avenue des Arts 56, 1000 Brussels, Belgium", "+32 2 286 0500", "belgium.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The embassy covers consular services for Belgium-based applicants."),
    ("Brazil", "Australia"): ("Australian Embassy, Brasilia", "SES Quadra 801, Conjunto K, Lote 07, 70200-010 Brasília, Brazil", "+55 61 3226 3111", "brazil.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Consular services available at the embassy in Brasilia."),
    ("Canada", "Australia"): ("Australian High Commission, Ottawa", "Suite 1301, 50 O'Connor Street, Ottawa, ON K1P 6L2, Canada", "+1 613 236 0841", "canada.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The High Commission handles consular matters only."),
    ("Chile", "Australia"): ("Australian Embassy, Santiago", "Isidora Goyenechea 3621, Piso 13, Las Condes, Santiago, Chile", "+56 2 2550 3500", "chile.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Visit the embassy for consular assistance."),
    ("Czech Republic", "Australia"): ("Australian Embassy, Prague", "Senovážné náměstí 28, 110 00 Prague 1, Czech Republic", "+420 221 729 260", "czechrepublic.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Embassy covers consular services for Czech applicants."),
    ("Denmark", "Australia"): ("Australian Embassy, Copenhagen", "Dampfærgevej 26, 2100 Copenhagen, Denmark", "+45 7026 3676", "denmark.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Contact the embassy for consular matters."),
    ("Finland", "Australia"): ("Australian Embassy, Helsinki", "Museokatu 25B, 00100 Helsinki, Finland", "+358 9 4777 6640", "finland.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Finnish applicants should submit visas through the online portal."),
    ("France", "Australia"): ("Australian Embassy, Paris", "4 Rue Jean Rey, 75724 Paris Cedex 15, France", "+33 1 40 59 33 00", "france.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The embassy's consular section is open weekdays 09:00–12:00."),
    ("Germany", "Australia"): ("Australian Embassy, Berlin", "Wallstrasse 76-79, 10179 Berlin, Germany", "+49 30 880 088 0", "germany.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Consular hours: Mon–Thu 9:00–12:00 & 14:00–16:00, Fri 9:00–12:00."),
    ("Hong Kong", "Australia"): ("Australian Consulate-General, Hong Kong", "24th Floor, Harbour Centre, 25 Harbour Road, Wanchai, Hong Kong", "+852 2585 4139", "hongkong.china.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au or through VFS Global. Consulate counter hours: Mon–Fri 8:30–12:00."),
    ("Hungary", "Australia"): ("Australian Embassy, Budapest", "Királyliget 8-9, 1126 Budapest, Hungary", "+36 1 457 9777", "hungary.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Contact the embassy for consular assistance."),
    ("Ireland", "Australia"): ("Australian Embassy, Dublin", "7th Floor, Fitzwilton House, Wilton Terrace, Dublin 2, Ireland", "+353 1 664 5300", "ireland.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The embassy handles consular matters for Ireland-based applicants."),
    ("Italy", "Australia"): ("Australian Embassy, Rome", "Via Antonio Bosio 5, 00161 Rome, Italy", "+39 06 852 721", "italy.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Consular services available at the embassy in Rome."),
    ("Japan", "Australia"): ("Australian Embassy, Tokyo", "2-1-14 Mita, Minato-ku, Tokyo 108-8361, Japan", "+81 3 5232 4111", "japan.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The embassy handles consular matters; visa queries are managed by the South Korea office."),
    ("Mainland China", "Australia"): ("Australian Embassy, Beijing", "21 Dongzhimenwai Dajie, Chaoyang District, Beijing 100600, China", "+86 10 5140 4111", "china.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au or through VFS Global offices in major Chinese cities."),
    ("Netherlands", "Australia"): ("Australian Embassy, The Hague", "Carnegielaan 4, 2517 KH The Hague, Netherlands", "+31 70 310 8200", "netherlands.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Contact the embassy in The Hague for consular matters."),
    ("New Zealand", "Australia"): ("Australian High Commission, Wellington", "72-76 Hobson Street, Thorndon, Wellington 6011, New Zealand", "+64 4 473 6411", "newzealand.embassy.gov.au", "New Zealand citizens have special visa-free arrangements. Visit immi.homeaffairs.gov.au for working rights details."),
    ("Norway", "Australia"): ("Australian Embassy, Oslo", "Brynjulf Bulls plass 2, 0250 Oslo, Norway", "+47 22 47 91 70", "norway.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Contact the Oslo embassy for consular assistance."),
    ("Poland", "Australia"): ("Australian Embassy, Warsaw", "Ul. Nowogrodzka 11, 00-513 Warsaw, Poland", "+48 22 521 3444", "poland.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Polish WHV applicants use the online portal."),
    ("Portugal", "Australia"): ("Australian Embassy, Lisbon", "Av. da Liberdade 200, 2nd Floor, 1250-147 Lisbon, Portugal", "+351 21 310 1500", "portugal.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Contact the Lisbon embassy for consular matters."),
    ("Singapore", "Australia"): ("Australian High Commission, Singapore", "25 Napier Road, Singapore 258507", "+65 6836 4100", "singapore.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The High Commission handles consular services for Singapore-based applicants."),
    ("Slovakia", "Australia"): ("Australian Embassy, Bratislava", "Kollárovo námestie 10, 811 06 Bratislava, Slovakia", "+421 2 5930 3900", "slovakia.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Slovakia applicants submit visas through the online portal."),
    ("South Korea", "Australia"): ("Australian Embassy, Seoul", "19th Floor, Kyobo Building, 1 Jong-Ro, Jongno-gu, Seoul 03154", "+82 2 2003 0100", "southkorea.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Visa enquiries: +82 2 2003 0111, Mon–Fri 9:00–12:00."),
    ("Spain", "Australia"): ("Australian Embassy, Madrid", "Torre Espacio, Paseo de la Castellana 259D, 28046 Madrid, Spain", "+34 91 353 6600", "spain.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Contact the Madrid embassy for consular assistance."),
    ("Sweden", "Australia"): ("Australian Embassy, Stockholm", "Klarabergsviadukten 63, 101 23 Stockholm, Sweden", "+46 8 613 2900", "sweden.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Contact the Stockholm embassy for consular matters."),
    ("Taiwan", "Australia"): ("Australian Office, Taipei", "Suite 2612, 26th Floor, International Trade Building, Taipei", "+886 2 8725 4100", "australia.org.tw", "Apply online via immi.homeaffairs.gov.au. The Australian Office in Taipei provides consular services."),
    ("United Kingdom", "Australia"): ("Australian High Commission, London", "Australia House, The Strand, London WC2B 4LA, United Kingdom", "+44 20 7379 4334", "uk.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. The High Commission handles consular matters; visa queries: +61 2 6196 0196."),
    ("USA", "Australia"): ("Australian Embassy, Washington D.C.", "1601 Massachusetts Avenue NW, Washington, DC 20036, USA", "+1 202 797 3000", "usa.embassy.gov.au", "Apply online via immi.homeaffairs.gov.au. Also apply through Australian consulates in New York, Los Angeles, Chicago, Houston, San Francisco."),

    # New Zealand as destination
    ("Argentina", "New Zealand"): ("New Zealand Embassy, Buenos Aires", "Carlos Pellegrini 1427, Piso 5, C1011AAC Buenos Aires, Argentina", "+54 11 4328 0747", "mfat.govt.nz/argentina", "Apply online at immigration.govt.nz. The embassy handles consular matters for Argentina-based applicants."),
    ("Australia", "New Zealand"): ("New Zealand High Commission, Canberra", "Commonwealth Avenue, Canberra ACT 2600, Australia", "+61 2 6270 4211", "nzembassy.com/australia", "Australian citizens have a special arrangement. Visit immigration.govt.nz for working rights and visa details."),
    ("Austria", "New Zealand"): ("New Zealand Embassy, Vienna", "Salesianergasse 15/3, 1030 Vienna, Austria", "+43 1 318 8505", "mfat.govt.nz", "Apply online at immigration.govt.nz. Austrian WHV applicants use the NZ online visa portal."),
    ("Belgium", "New Zealand"): ("New Zealand Embassy, Brussels", "Rue des Aduatiques 85, 1040 Brussels, Belgium", "+32 2 512 1040", "mfat.govt.nz", "Apply online at immigration.govt.nz. The NZ Embassy in Brussels handles consular services."),
    ("Brazil", "New Zealand"): ("New Zealand Embassy, Brasilia", "SHIS QI 09, Conjunto 16, Casa 01, 71625-160 Brasília, Brazil", "+55 61 3248 9900", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Brasilia embassy for consular assistance."),
    ("Canada", "New Zealand"): ("New Zealand High Commission, Ottawa", "150 Elgin Street, Suite 1401, Ottawa, ON K2P 1L4, Canada", "+1 613 238 5991", "nzembassy.com/canada", "Apply online at immigration.govt.nz. The High Commission handles consular matters."),
    ("Chile", "New Zealand"): ("New Zealand Embassy, Santiago", "Av. El Golf 99, Piso 12, Las Condes, Santiago, Chile", "+56 2 2616 3000", "mfat.govt.nz", "Apply online at immigration.govt.nz. Chilean WHV applicants use the NZ online visa portal."),
    ("Czech Republic", "New Zealand"): ("New Zealand Embassy, Prague", "Václavské náměstí 11, 110 00 Prague 1, Czech Republic", "+420 222 514 672", "mfat.govt.nz", "Apply online at immigration.govt.nz. Czech Republic applicants submit via the online portal."),
    ("Denmark", "New Zealand"): ("New Zealand Embassy, Copenhagen", "Strandvejen 6, 2900 Hellerup, Copenhagen, Denmark", "+45 3520 0222", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Copenhagen embassy for consular matters."),
    ("Finland", "New Zealand"): ("New Zealand Embassy, Helsinki", "Unioninkatu 20-22, 00130 Helsinki, Finland", "+358 9 6831 3500", "mfat.govt.nz", "Apply online at immigration.govt.nz. Finnish WHV applicants submit via the NZ online visa portal."),
    ("France", "New Zealand"): ("New Zealand Embassy, Paris", "103 Rue de Grenelle, 75007 Paris, France", "+33 1 45 01 43 43", "mfat.govt.nz/france", "Apply online at immigration.govt.nz. The embassy handles consular matters for France-based applicants."),
    ("Germany", "New Zealand"): ("New Zealand Embassy, Berlin", "Atrium, 4th Floor, Friedrichstrasse 60, 10117 Berlin, Germany", "+49 30 206 210", "mfat.govt.nz/germany", "Apply online at immigration.govt.nz. The Berlin embassy covers Germany, Czech Republic, Liechtenstein and Switzerland."),
    ("Hong Kong", "New Zealand"): ("New Zealand Consulate-General, Hong Kong", "Room 6501, 65/F, Central Plaza, 18 Harbour Road, Wanchai, Hong Kong", "+852 2525 5044", "mfat.govt.nz", "Apply online at immigration.govt.nz. The NZ Consulate-General handles consular services for Hong Kong applicants."),
    ("Hungary", "New Zealand"): ("New Zealand Embassy, Budapest", "Népfürdő utca 22, Bank Center, Granite Tower, 1138 Budapest, Hungary", "+36 1 302 2484", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Budapest embassy for consular assistance."),
    ("Ireland", "New Zealand"): ("New Zealand Embassy, Dublin", "76 Merrion Square South, Dublin 2, Ireland", "+353 1 676 2464", "mfat.govt.nz", "Apply online at immigration.govt.nz. The Dublin embassy handles consular matters for Irish applicants."),
    ("Italy", "New Zealand"): ("New Zealand Embassy, Rome", "Via Clitunno 44, 00198 Rome, Italy", "+39 06 853 7501", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Rome embassy for consular assistance."),
    ("Japan", "New Zealand"): ("New Zealand Embassy, Tokyo", "20-40 Kamiyama-cho, Shibuya-ku, Tokyo 150-0047, Japan", "+81 3 3467 2271", "mfat.govt.nz/japan", "Apply online at immigration.govt.nz. The Tokyo embassy handles consular matters for Japan-based applicants."),
    ("Mainland China", "New Zealand"): ("New Zealand Embassy, Beijing", "Ritan Donglu 1, Chaoyang District, Beijing 100600, China", "+86 10 8532 8300", "mfat.govt.nz", "Apply online at immigration.govt.nz or through VFS Global in major Chinese cities."),
    ("Malaysia", "New Zealand"): ("New Zealand High Commission, Kuala Lumpur", "Level 21, Menara IMC, 8 Jalan Sultan Ismail, 50250 Kuala Lumpur, Malaysia", "+60 3 2078 2533", "mfat.govt.nz", "Apply online at immigration.govt.nz. The High Commission handles consular services for Malaysian applicants."),
    ("Netherlands", "New Zealand"): ("New Zealand Embassy, The Hague", "Eisenhowerlaan 77N, 2517 KK The Hague, Netherlands", "+31 70 346 9324", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the The Hague embassy for consular matters."),
    ("Norway", "New Zealand"): ("New Zealand Embassy, Oslo", "Haakon VIIs gate 5, 0161 Oslo, Norway", "+47 22 01 39 00", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Oslo embassy for consular assistance."),
    ("Philippines", "New Zealand"): ("New Zealand Embassy, Manila", "18th Floor, The Enterprise Center, 6766 Ayala Avenue, Makati City, Manila", "+63 2 891 5358", "mfat.govt.nz", "Apply online at immigration.govt.nz. The Manila embassy handles consular matters for Filipino applicants."),
    ("Poland", "New Zealand"): ("New Zealand Embassy, Warsaw", "Al. Ujazdowskie 51, 00-536 Warsaw, Poland", "+48 22 521 0500", "mfat.govt.nz", "Apply online at immigration.govt.nz. Polish WHV applicants use the NZ online visa portal."),
    ("Portugal", "New Zealand"): ("New Zealand Embassy, Lisbon", "Avenida da Liberdade 144, 4th Floor, 1269-059 Lisbon, Portugal", "+351 21 357 6980", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Lisbon embassy for consular matters."),
    ("Singapore", "New Zealand"): ("New Zealand High Commission, Singapore", "391A Orchard Road, #15-02 Ngee Ann City Tower A, Singapore 238873", "+65 6235 9966", "mfat.govt.nz", "Apply online at immigration.govt.nz. The High Commission handles consular services for Singapore applicants."),
    ("Slovakia", "New Zealand"): ("New Zealand Embassy, Bratislava", "Paulínska 20, 917 01 Trnava, Slovakia", "+421 33 593 1000", "mfat.govt.nz", "Apply online at immigration.govt.nz. Slovak WHV applicants use the NZ online visa portal."),
    ("South Korea", "New Zealand"): ("New Zealand Embassy, Seoul", "Level 20, 171 Featherston Street, Wellington (Seoul: Jeokseon-dong 5-1, Jongno-gu)", "+64 4 473 9073", "mfat.govt.nz/south-korea", "Apply online at immigration.govt.nz. Contact the NZ Embassy in Seoul: +82 2 3701 7700."),
    ("Spain", "New Zealand"): ("New Zealand Embassy, Madrid", "Pinar 7, 3rd Floor, 28006 Madrid, Spain", "+34 91 523 0226", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Madrid embassy for consular assistance."),
    ("Sweden", "New Zealand"): ("New Zealand Embassy, Stockholm", "Nybrogatan 11, 114 39 Stockholm, Sweden", "+46 8 611 2625", "mfat.govt.nz", "Apply online at immigration.govt.nz. Contact the Stockholm embassy for consular matters."),
    ("Taiwan", "New Zealand"): ("New Zealand Commerce & Industry Office, Taipei", "Room A, 25/F, Taipei 101 Tower, No. 7, Sec. 5, Xinyi Road, Taipei 11049", "+886 2 2720 5228", "mfat.govt.nz", "Apply online at immigration.govt.nz. The NZ Commerce & Industry Office provides consular services in Taiwan."),
    ("United Kingdom", "New Zealand"): ("New Zealand High Commission, London", "Kinnaird House, 1 Pall Mall East, London SW1Y 5AU, United Kingdom", "+44 20 7968 2730", "mfat.govt.nz/uk", "Apply online at immigration.govt.nz. The High Commission handles consular matters for UK-based applicants."),
    ("USA", "New Zealand"): ("New Zealand Embassy, Washington D.C.", "37 Observatory Circle NW, Washington, DC 20008, USA", "+1 202 328 4800", "mfat.govt.nz/usa", "Apply online at immigration.govt.nz. Also contact NZ consulates in Los Angeles, New York, and San Francisco."),

    # Japan as destination
    ("Argentina", "Japan"): ("Embassy of Japan, Buenos Aires", "Bouchard 547, Piso 17, C1106ABG Buenos Aires, Argentina", "+54 11 4318 8200", "ar.emb-japan.go.jp", "Apply through the Japanese Embassy in Buenos Aires. Working Holiday visa requires advance application before arrival."),
    ("Australia", "Japan"): ("Embassy of Japan, Canberra", "112 Empire Circuit, Yarralumla, ACT 2600, Australia", "+61 2 6273 3244", "au.emb-japan.go.jp", "Apply through the Japanese Embassy or Consulate-General nearest to your residence. WHV requires application before departure."),
    ("Austria", "Japan"): ("Embassy of Japan, Vienna", "Hessgasse 6, 1010 Vienna, Austria", "+43 1 531 920", "austria.emb-japan.go.jp", "Apply through the Japanese Embassy in Vienna. Working Holiday visa must be obtained before traveling to Japan."),
    ("Canada", "Japan"): ("Embassy of Japan, Ottawa", "255 Sussex Drive, Ottawa, ON K1N 9E6, Canada", "+1 613 241 8541", "ca.emb-japan.go.jp", "Apply through the Japanese Embassy or the nearest Consulate-General. WHV applications require in-person submission."),
    ("Chile", "Japan"): ("Embassy of Japan, Santiago", "Av. Ricardo Lyon 520, Providencia, Santiago, Chile", "+56 2 2232 1807", "cl.emb-japan.go.jp", "Apply through the Japanese Embassy in Santiago. Working Holiday visa must be obtained before departure."),
    ("Czech Republic", "Japan"): ("Embassy of Japan, Prague", "Maltézské náměstí 6, 118 01 Prague 1, Czech Republic", "+420 257 533 546", "cz.emb-japan.go.jp", "Apply through the Japanese Embassy in Prague. WHV requires in-person application before departure."),
    ("Denmark", "Japan"): ("Embassy of Japan, Copenhagen", "Pilestræde 61, 1112 Copenhagen, Denmark", "+45 33 11 33 44", "dk.emb-japan.go.jp", "Apply through the Japanese Embassy in Copenhagen. Working Holiday visa must be obtained before traveling."),
    ("Estonia", "Japan"): ("Embassy of Japan, Tallinn", "Harju tn 6, 10130 Tallinn, Estonia", "+372 631 0531", "ee.emb-japan.go.jp", "Apply through the Japanese Embassy in Tallinn. WHV must be obtained before departure to Japan."),
    ("France", "Japan"): ("Embassy of Japan, Paris", "7 Avenue Hoche, 75008 Paris, France", "+33 1 48 88 62 00", "fr.emb-japan.go.jp", "Apply through the Japanese Embassy or Consulate-General nearest to your residence. WHV requires advance application."),
    ("Germany", "Japan"): ("Embassy of Japan, Berlin", "Hiroshimastrasse 6, 10785 Berlin, Germany", "+49 30 210 940", "de.emb-japan.go.jp", "Apply through the Japanese Embassy in Berlin or a Consulate-General. WHV requires advance application before departure."),
    ("Hong Kong", "Japan"): ("Embassy of Japan, Hong Kong (Consulate-General)", "Level 47, One Exchange Square, 8 Connaught Place, Central, Hong Kong", "+852 2522 1184", "hk.emb-japan.go.jp", "Apply through the Consulate-General of Japan in Hong Kong. WHV requires in-person application before departure."),
    ("Hungary", "Japan"): ("Embassy of Japan, Budapest", "Zalán utca 7, 1022 Budapest, Hungary", "+36 1 398 3100", "hu.emb-japan.go.jp", "Apply through the Japanese Embassy in Budapest. Working Holiday visa must be obtained before traveling to Japan."),
    ("Iceland", "Japan"): ("Embassy of Japan, Reykjavik", "Laufásvegur 31, 101 Reykjavik, Iceland", "+354 510 4500", "is.emb-japan.go.jp", "Apply through the Japanese Embassy in Reykjavik. WHV requires advance application before departure."),
    ("Ireland", "Japan"): ("Embassy of Japan, Dublin", "Merrion Centre, Nutley Lane, Dublin 4, Ireland", "+353 1 202 8300", "ie.emb-japan.go.jp", "Apply through the Japanese Embassy in Dublin. Working Holiday visa requires application before departure."),
    ("Latvia", "Japan"): ("Embassy of Japan, Riga", "Pernavas 15A-100, Riga, LV-1011, Latvia", "+371 6706 0200", "lv.emb-japan.go.jp", "Apply through the Japanese Embassy in Riga. WHV must be obtained before departure to Japan."),
    ("Lithuania", "Japan"): ("Embassy of Japan, Vilnius", "Gynėjų 16, 01109 Vilnius, Lithuania", "+370 5 279 0418", "lt.emb-japan.go.jp", "Apply through the Japanese Embassy in Vilnius. Working Holiday visa must be obtained before departure."),
    ("Netherlands", "Japan"): ("Embassy of Japan, The Hague", "Tobias Asserlaan 2, 2517 KC The Hague, Netherlands", "+31 70 346 9544", "nl.emb-japan.go.jp", "Apply through the Japanese Embassy in The Hague. WHV requires advance application before traveling."),
    ("New Zealand", "Japan"): ("Embassy of Japan, Wellington", "Level 18, The Majestic Centre, 100 Willis Street, Wellington 6011", "+64 4 473 1540", "nz.emb-japan.go.jp", "Apply through the Japanese Embassy or Consulate-General in Auckland. WHV requires application before departure."),
    ("Norway", "Japan"): ("Embassy of Japan, Oslo", "Haakon VIIs gate 9, 0161 Oslo, Norway", "+47 22 01 29 00", "no.emb-japan.go.jp", "Apply through the Japanese Embassy in Oslo. Working Holiday visa must be obtained before traveling to Japan."),
    ("Poland", "Japan"): ("Embassy of Japan, Warsaw", "ul. Szwolezerów 8, 00-464 Warsaw, Poland", "+48 22 696 5000", "pl.emb-japan.go.jp", "Apply through the Japanese Embassy in Warsaw. WHV requires in-person application before departure."),
    ("Portugal", "Japan"): ("Embassy of Japan, Lisbon", "Avenida da Liberdade 6, 2nd Floor, 1250-145 Lisbon, Portugal", "+351 21 311 0560", "pt.emb-japan.go.jp", "Apply through the Japanese Embassy in Lisbon. Working Holiday visa must be obtained before traveling to Japan."),
    ("Slovakia", "Japan"): ("Embassy of Japan, Bratislava", "Hlavné námestie 2, 811 01 Bratislava, Slovakia", "+421 2 5980 0900", "sk.emb-japan.go.jp", "Apply through the Japanese Embassy in Bratislava. WHV requires advance application before departure."),
    ("South Korea", "Japan"): ("Embassy of Japan, Seoul", "Twin Tree Tower A, 6 Yulgok-ro, Jongno-gu, Seoul, South Korea", "+82 2 739 7400", "kr.emb-japan.go.jp", "Apply through the Japanese Embassy or a Consulate-General in South Korea. WHV requires advance application."),
    ("Spain", "Japan"): ("Embassy of Japan, Madrid", "Serrano 109, 28006 Madrid, Spain", "+34 91 590 7600", "es.emb-japan.go.jp", "Apply through the Japanese Embassy in Madrid. Working Holiday visa must be obtained before departure."),
    ("Sweden", "Japan"): ("Embassy of Japan, Stockholm", "Gardesgatan 10, 115 27 Stockholm, Sweden", "+46 8 579 352 00", "se.emb-japan.go.jp", "Apply through the Japanese Embassy in Stockholm. WHV requires advance application before traveling to Japan."),
    ("Taiwan", "Japan"): ("Japan-Taiwan Exchange Association, Taipei", "43F, Taipei 101, No. 7, Sec. 5, Xinyi Road, Taipei 11049", "+886 2 2713 8000", "koryu.or.jp/taiwan", "Apply through the Japan-Taiwan Exchange Association in Taipei. WHV requires advance application."),
    ("United Kingdom", "Japan"): ("Embassy of Japan, London", "101-104 Piccadilly, London W1J 7JT, United Kingdom", "+44 20 7465 6565", "uk.emb-japan.go.jp", "Apply through the Japanese Embassy or Consulate-General in Edinburgh. WHV requires appointment and advance application."),
    ("Uruguay", "Japan"): ("Embassy of Japan, Montevideo", "Av. Dr. Luis A. de Herrera 1248, World Trade Center, Torre 4, Piso 22, Montevideo, Uruguay", "+598 2 915 0075", "uy.emb-japan.go.jp", "Apply through the Japanese Embassy in Montevideo. Working Holiday visa must be obtained before departure."),

    # South Korea as destination
    ("Argentina", "South Korea"): ("Embassy of the Republic of Korea, Buenos Aires", "Del Libertador 2395, C1425 Buenos Aires, Argentina", "+54 11 4802 8865", "overseas.mofa.go.kr/ar-es", "Apply through the Korean Embassy in Buenos Aires. Submit WHV application in person with all required documents."),
    ("Australia", "South Korea"): ("Embassy of the Republic of Korea, Canberra", "Level 3, 42 Macquarie Street, Barton ACT 2600, Australia", "+61 2 6270 4100", "overseas.mofa.go.kr/au-en", "Apply through the Korean Embassy in Canberra or Consulate-General in Sydney. Visa applications Mon–Fri 09:00–12:30."),
    ("Austria", "South Korea"): ("Embassy of the Republic of Korea, Vienna", "Praterstrasse 31, 1020 Vienna, Austria", "+43 1 478 1991", "overseas.mofa.go.kr/at-de", "Apply through the Korean Embassy in Vienna. WHV requires in-person application with required documents."),
    ("Belgium", "South Korea"): ("Embassy of the Republic of Korea, Brussels", "Chaussée de la Hulpe 173-175, 1170 Brussels, Belgium", "+32 2 675 5777", "overseas.mofa.go.kr/be-fr", "Apply through the Korean Embassy in Brussels. Submit WHV application in person before departure."),
    ("Canada", "South Korea"): ("Embassy of the Republic of Korea, Ottawa", "150 Boteler Street, Ottawa, ON K1N 5A6, Canada", "+1 613 244 5010", "overseas.mofa.go.kr/ca-en", "Apply through the Korean Embassy in Ottawa or Consulate-General in Toronto, Vancouver, or Montreal."),
    ("Chile", "South Korea"): ("Embassy of the Republic of Korea, Santiago", "Alcántara 74, Las Condes, Santiago, Chile", "+56 2 2228 4214", "overseas.mofa.go.kr/cl-es", "Apply through the Korean Embassy in Santiago. WHV requires in-person application before departure."),
    ("Czech Republic", "South Korea"): ("Embassy of the Republic of Korea, Prague", "Slavíčkova 5, 160 00 Prague 6, Czech Republic", "+420 234 090 411", "overseas.mofa.go.kr/cz-cs", "Apply through the Korean Embassy in Prague. Submit WHV application in person with required documents."),
    ("Denmark", "South Korea"): ("Embassy of the Republic of Korea, Copenhagen", "Svanemøllevej 104, 2900 Hellerup, Copenhagen, Denmark", "+45 3946 0400", "overseas.mofa.go.kr/dk-da", "Apply through the Korean Embassy in Copenhagen. WHV requires advance in-person application."),
    ("France", "South Korea"): ("Embassy of the Republic of Korea, Paris", "41-43 Rue Saint Dominique, 75007 Paris, France", "+33 1 47 53 01 01", "overseas.mofa.go.kr/fr-fr", "Apply through the Korean Embassy in Paris. WHV requires in-person application before departure to South Korea."),
    ("Germany", "South Korea"): ("Embassy of the Republic of Korea, Berlin", "Stülerstrasse 8/10, 10787 Berlin, Germany", "+49 30 26065 0", "overseas.mofa.go.kr/de-de", "Apply through the Korean Embassy in Berlin or the Korea Visa Application Centre. WHV applications require advance submission."),
    ("Hong Kong", "South Korea"): ("Consulate-General of the Republic of Korea, Hong Kong", "5/F, Far East Finance Centre, 16 Harcourt Road, Admiralty, Hong Kong", "+852 2529 4141", "overseas.mofa.go.kr/hk-zh", "Apply through the Korean Consulate-General in Hong Kong. WHV requires in-person application."),
    ("Hungary", "South Korea"): ("Embassy of the Republic of Korea, Budapest", "Andrássy út 109, 1062 Budapest, Hungary", "+36 1 351 1182", "overseas.mofa.go.kr/hu-hu", "Apply through the Korean Embassy in Budapest. Submit WHV application in person before departure."),
    ("Ireland", "South Korea"): ("Embassy of the Republic of Korea, Dublin", "15 Clyde Road, Ballsbridge, Dublin 4, Ireland", "+353 1 660 8800", "overseas.mofa.go.kr/ie-en", "Apply through the Korean Embassy in Dublin. WHV requires in-person application with required documents."),
    ("Italy", "South Korea"): ("Embassy of the Republic of Korea, Rome", "Via Barnaba Oriani 30, 00197 Rome, Italy", "+39 06 802 461", "overseas.mofa.go.kr/it-it", "Apply through the Korean Embassy in Rome. WHV requires in-person application before departure."),
    ("Japan", "South Korea"): ("Embassy of the Republic of Korea, Tokyo", "1-2-5 Minami-Azabu, Minato-ku, Tokyo 106-8577, Japan", "+81 3 3452 7611", "overseas.mofa.go.kr/jp-ja", "Apply through the Korean Embassy in Tokyo or Consulate-General in Osaka, Nagoya, Fukuoka, Sapporo, or Hiroshima."),
    ("Netherlands", "South Korea"): ("Embassy of the Republic of Korea, The Hague", "Verlengde Tolweg 8, 2517 JV The Hague, Netherlands", "+31 70 358 6076", "overseas.mofa.go.kr/nl-nl", "Apply through the Korean Embassy in The Hague. WHV requires in-person application before departure."),
    ("New Zealand", "South Korea"): ("Embassy of the Republic of Korea, Wellington", "Level 20, 171 Featherston Street, Wellington 6011, New Zealand", "+64 4 473 9073", "overseas.mofa.go.kr/nz-en", "Apply through the Korean Embassy in Wellington. WHV applications accepted Mon–Fri 09:00–12:00."),
    ("Poland", "South Korea"): ("Embassy of the Republic of Korea, Warsaw", "Szwolezerow 6, 00-464 Warsaw, Poland", "+48 22 559 2600", "overseas.mofa.go.kr/pl-pl", "Apply through the Korean Embassy in Warsaw. WHV requires in-person application with all documents."),
    ("Portugal", "South Korea"): ("Embassy of the Republic of Korea, Lisbon", "Av. Miguel Bombarda 36-7, 1050-165 Lisbon, Portugal", "+351 21 793 7200", "overseas.mofa.go.kr/pt-pt", "Apply through the Korean Embassy in Lisbon. WHV requires in-person application before departure."),
    ("Spain", "South Korea"): ("Embassy of the Republic of Korea, Madrid", "Gonzalez Amigo 15, 28033 Madrid, Spain", "+34 91 353 2000", "overseas.mofa.go.kr/es-es", "Apply through the Korean Embassy in Madrid. WHV requires in-person application with required documents."),
    ("Sweden", "South Korea"): ("Embassy of the Republic of Korea, Stockholm", "Laboratoriegatan 10, 115 27 Stockholm, Sweden", "+46 8 660 9770", "overseas.mofa.go.kr/se-sv", "Apply through the Korean Embassy in Stockholm. WHV requires advance in-person application."),
    ("Taiwan", "South Korea"): ("Korea Mission in Taipei (MOFA)", "6F, 333 Keelung Road, Sec. 1, Xinyi District, Taipei 11012", "+886 2 2758 8320", "overseas.mofa.go.kr/tw-zh", "Apply through the Korean Mission in Taipei. WHV requires in-person application before departure."),
    ("United Kingdom", "South Korea"): ("Embassy of the Republic of Korea, London", "60 Buckingham Gate, London SW1E 6AJ, United Kingdom", "+44 20 7227 5500", "overseas.mofa.go.kr/gb-en", "Apply through the Korean Embassy in London. WHV applications accepted Mon–Fri 09:00–12:00. UK residents outside London may use the Korea Visa Application Centre."),
    ("USA", "South Korea"): ("Embassy of the Republic of Korea, Washington D.C.", "2450 Massachusetts Avenue NW, Washington, DC 20008, USA", "+1 202 939 5600", "overseas.mofa.go.kr/us-en", "Apply through the Korean Embassy or Consulate-General in Los Angeles, New York, Chicago, Atlanta, San Francisco, Seattle, Boston, or Houston."),

    # Germany as destination
    ("Argentina", "Germany"): ("Embassy of Germany, Buenos Aires", "Villanueva 1055, C1426BMC Buenos Aires, Argentina", "+54 11 4778 2500", "buenos-aires.diplo.de", "Apply via VFS Global in Buenos Aires. Long-stay WHV requires appointment at the German Embassy."),
    ("Australia", "Germany"): ("Embassy of Germany, Canberra", "119 Empire Circuit, Yarralumla ACT 2600, Australia", "+61 2 6270 1911", "australia.diplo.de", "Apply via VFS Global in Australia. Long-stay WHV requires appointment at the German Embassy in Canberra."),
    ("Austria", "Germany"): ("Embassy of Germany, Vienna", "Gauermanngasse 2-4, 1010 Vienna, Austria", "+43 1 711 540", "wien.diplo.de", "Austrian citizens have freedom of movement within the EU/EEA. Contact the embassy for long-stay work permits."),
    ("Brazil", "Germany"): ("Embassy of Germany, Brasilia", "SES Av. das Nações, Quadra 807, Lote 25, 70415-900 Brasília, Brazil", "+55 61 3442 7000", "brasilien.diplo.de", "Apply at the German Embassy or Consulate-General in São Paulo. WHV requires an appointment and advance application."),
    ("Canada", "Germany"): ("Embassy of Germany, Ottawa", "1 Waverley Street, Ottawa, ON K2P 0T8, Canada", "+1 613 232 1101", "kanada.diplo.de", "Apply at the German Consulate-General in Toronto. Long-stay visas including WHV require in-person applications."),
    ("Chile", "Germany"): ("Embassy of Germany, Santiago", "Las Hualtatas 5677, Vitacura, Santiago, Chile", "+56 2 2463 2500", "santiago.diplo.de", "Apply at the German Embassy in Santiago. WHV requires an appointment and advance application before departure."),
    ("Hong Kong", "Germany"): ("German Consulate-General, Hong Kong", "21/F Jardine House, 1 Connaught Place, Central, Hong Kong", "+852 2105 8788", "hongkong.diplo.de", "Apply at the German Consulate-General in Hong Kong. WHV requires an appointment and in-person application."),
    ("Israel", "Germany"): ("Embassy of Germany, Tel Aviv", "3 Daniel Frisch Street, 6473104 Tel Aviv, Israel", "+972 3 693 9999", "israel.diplo.de", "Apply at the German Embassy in Tel Aviv. WHV requires an appointment and advance in-person application."),
    ("Japan", "Germany"): ("Embassy of Germany, Tokyo", "4-5-10 Minami-Azabu, Minato-ku, Tokyo 106-0047, Japan", "+81 3 5791 7700", "japan.diplo.de", "Apply at the German Embassy in Tokyo or the Consulate-General in Osaka. WHV requires an appointment and advance application."),
    ("Mainland China", "Germany"): ("Embassy of Germany, Beijing", "17 Dongzhimenwai Dajie, Chaoyang District, Beijing 100600, China", "+86 10 8532 9000", "china.diplo.de", "Apply at the German Embassy in Beijing or Consulate-General in Shanghai, Guangzhou, Chengdu, or Shenyang."),
    ("New Zealand", "Germany"): ("Embassy of Germany, Wellington", "90-92 Hobson Street, Thorndon, Wellington 6011, New Zealand", "+64 4 473 6063", "wellington.diplo.de", "Apply at the German Embassy in Wellington. WHV requires an appointment. Apply online via the appointment system."),
    ("Singapore", "Germany"): ("Embassy of Germany, Singapore", "50 Raffles Place, #29-00 Singapore Land Tower, Singapore 048623", "+65 6533 6002", "singapur.diplo.de", "Apply at the German Embassy in Singapore. WHV requires an appointment and advance in-person application."),
    ("South Korea", "Germany"): ("Embassy of Germany, Seoul", "8F, Seoul Square, 416 Hangang-daero, Jung-gu, Seoul 04637", "+82 2 748 4114", "seoul.diplo.de", "Apply at the German Embassy in Seoul. WHV requires an appointment. Korea Visa Application Centre also available in Seoul."),
    ("Taiwan", "Germany"): ("German Institute Taipei", "20F, 333 Keelung Road, Sec. 1, Xinyi District, Taipei 11012", "+886 2 8722 2800", "taipei.diplo.de", "Apply at the German Institute Taipei. WHV requires an appointment and advance in-person application."),
    ("United Kingdom", "Germany"): ("Embassy of Germany, London", "23 Belgrave Square, London SW1X 8PZ, United Kingdom", "+44 20 7824 1300", "london.diplo.de", "Apply via TLScontact Visa Application Centres in London, Manchester, or Edinburgh. WHV requires advance application."),
    ("Uruguay", "Germany"): ("Embassy of Germany, Montevideo", "La Cumparsita 1435, 11200 Montevideo, Uruguay", "+598 2 902 5222", "montevideo.diplo.de", "Apply at the German Embassy in Montevideo. WHV requires an appointment and advance in-person application."),
    ("USA", "Germany"): ("Embassy of Germany, Washington D.C.", "4645 Reservoir Road NW, Washington, DC 20007, USA", "+1 202 298 4000", "usa.diplo.de", "Apply at the German Embassy or Consulate-General in New York, Los Angeles, Chicago, Houston, San Francisco, Atlanta, Boston, or Miami."),

    # France as destination
    ("Argentina", "France"): ("Embassy of France, Buenos Aires", "Cerrito 1399, C1010ABA Buenos Aires, Argentina", "+54 11 4515 7000", "ar.ambafrance.org", "Apply via France-Visas portal (france-visas.gouv.fr). The embassy consular section handles visa appointments."),
    ("Australia", "France"): ("Embassy of France, Canberra", "6 Perth Avenue, Yarralumla, ACT 2600, Australia", "+61 2 6216 0100", "au.ambafrance.org", "Apply via France-Visas portal (france-visas.gouv.fr). The French Embassy handles WHV applications for Australian citizens."),
    ("Brazil", "France"): ("Embassy of France, Brasilia", "SES Av. das Nações, Quadra 801, Lote 04, 70404-900 Brasília, Brazil", "+55 61 3222 9100", "bresil.ambafrance.org", "Apply via France-Visas portal. Consulate-General in São Paulo also accepts applications."),
    ("Canada", "France"): ("Embassy of France, Ottawa", "42 Sussex Drive, Ottawa, ON K1M 2C9, Canada", "+1 613 789 1795", "ca.ambafrance.org", "Apply via France-Visas portal. Consulate-General in Toronto handles consular services for Ontario residents."),
    ("Chile", "France"): ("Embassy of France, Santiago", "Av. Condell 65, Providencia, Santiago, Chile", "+56 2 2470 8000", "cl.ambafrance.org", "Apply via France-Visas portal (france-visas.gouv.fr). The embassy handles WHV applications for Chilean citizens."),
    ("Colombia", "France"): ("Embassy of France, Bogota", "Carrera 11 No. 93-12, Bogotá, Colombia", "+57 1 638 1400", "co.ambafrance.org", "Apply via France-Visas portal. The French Embassy in Bogotá handles visa applications for Colombian citizens."),
    ("Hong Kong", "France"): ("Consulate-General of France, Hong Kong", "Admiralty Centre, Tower II, 25/F-26/F, 18 Harcourt Road, Central, Hong Kong", "+852 3752 9900", "france-hongkong.org", "Apply via TLScontact Hong Kong. Applications reviewed by the French Consulate-General in Hong Kong."),
    ("Japan", "France"): ("Embassy of France, Tokyo", "4-11-44 Minami-Azabu, Minato-ku, Tokyo 106-8514, Japan", "+81 3 5798 6000", "fr.ambafrance.org", "Apply via France-Visas portal. The embassy consular section is open weekdays 09:00–11:30."),
    ("Mexico", "France"): ("Embassy of France, Mexico City", "Campos Eliseos 339, Polanco, 11560 Mexico City, Mexico", "+52 55 9171 9700", "mx.ambafrance.org", "Apply via France-Visas portal. The French Embassy in Mexico City handles WHV applications."),
    ("New Zealand", "France"): ("Embassy of France, Wellington", "20 Ballance Street (Level 8), Wellington 6011, New Zealand", "+64 4 384 2555", "nz.ambafrance.org", "Apply via France-Visas portal. The Wellington embassy handles WHV applications for New Zealand citizens."),
    ("Peru", "France"): ("Embassy of France, Lima", "Arequipa 3415, San Isidro, Lima 27, Peru", "+51 1 215 8400", "pe.ambafrance.org", "Apply via France-Visas portal. The French Embassy in Lima handles visa applications for Peruvian citizens."),
    ("South Korea", "France"): ("Embassy of France, Seoul", "43-12 Seosomun-ro, Seodaemun-gu, Seoul 120-030, South Korea", "+82 2 3149 4300", "kr.ambafrance.org", "Apply via France-Visas portal. The Seoul embassy consular section handles WHV applications."),
    ("Taiwan", "France"): ("French Office in Taipei", "Taipei 101, 39F, No. 7 Xinyi Road, Sec. 5, Taipei 11049", "+886 2 3518 5151", "france-visas.gouv.fr/taiwan", "Apply via France-Visas portal. The French Office in Taipei handles WHV applications for Taiwanese citizens."),
    ("Uruguay", "France"): ("Embassy of France, Montevideo", "Urugayana 853, 11100 Montevideo, Uruguay", "+598 2 902 0077", "uy.ambafrance.org", "Apply via France-Visas portal. The French Embassy in Montevideo handles visa applications."),

    # Canada as destination
    ("Argentina", "Canada"): ("High Commission of Canada, Buenos Aires", "Tagle 2828, C1425EEH Buenos Aires, Argentina", "+54 11 4808 1000", "argentina.gc.ca", "Apply online at ircc.canada.ca. The High Commission provides consular assistance for Argentine applicants."),
    ("Australia", "Canada"): ("High Commission of Canada, Canberra", "Commonwealth Avenue, Canberra ACT 2600, Australia", "+61 2 6270 4000", "australia.gc.ca", "Apply online at ircc.canada.ca. The High Commission in Canberra handles consular matters for Australian applicants."),
    ("Austria", "Canada"): ("Embassy of Canada, Vienna", "Laurenzerberg 2, 1010 Vienna, Austria", "+43 1 531 383 000", "austria.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Vienna handles consular matters."),
    ("Belgium", "Canada"): ("Embassy of Canada, Brussels", "Avenue de Tervuren 2, 1040 Brussels, Belgium", "+32 2 741 0611", "belgium.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Brussels handles consular matters for Belgian applicants."),
    ("Chile", "Canada"): ("Embassy of Canada, Santiago", "Nueva Tajamar 481, Torre Norte, Piso 12, Las Condes, Santiago, Chile", "+56 2 2652 3800", "chile.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Chilean applicants."),
    ("Costa Rica", "Canada"): ("Embassy of Canada, San José", "Oficentro Ejecutivo La Sabana, Edificio 5, San José, Costa Rica", "+506 2242 4400", "costarica.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in San José handles consular matters."),
    ("Croatia", "Canada"): ("Embassy of Canada, Zagreb", "Prilaz Gjure Dezelica 4, 10000 Zagreb, Croatia", "+385 1 488 1200", "croatia.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Zagreb handles consular matters."),
    ("Czech Republic", "Canada"): ("Embassy of Canada, Prague", "Ve Struhách 95/2, 160 00 Prague 6, Czech Republic", "+420 272 101 800", "czechrepublic.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Czech applicants."),
    ("Denmark", "Canada"): ("Embassy of Canada, Copenhagen", "Kristen Bernikows Gade 1, 1105 Copenhagen, Denmark", "+45 3348 3200", "denmark.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Copenhagen handles consular matters."),
    ("Estonia", "Canada"): ("Embassy of Canada, Tallinn", "Toom-Kooli 13, 10130 Tallinn, Estonia", "+372 627 3311", "estonia.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Tallinn handles consular matters."),
    ("Finland", "Canada"): ("Embassy of Canada, Helsinki", "Pohjoisesplanadi 25B, 00100 Helsinki, Finland", "+358 9 228 530", "finland.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Finnish applicants."),
    ("France", "Canada"): ("Embassy of Canada, Paris", "130 Rue du Faubourg Saint-Honoré, 75008 Paris, France", "+33 1 44 43 29 00", "france.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for French applicants."),
    ("Germany", "Canada"): ("Embassy of Canada, Berlin", "Leipziger Platz 17, 10117 Berlin, Germany", "+49 30 20312 0", "germany.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters. Also contact Consulate-General in Munich or Düsseldorf."),
    ("Greece", "Canada"): ("Embassy of Canada, Athens", "4 Ioannou Gennadiou Street, 11521 Athens, Greece", "+30 210 727 3400", "greece.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Athens handles consular matters."),
    ("Hong Kong", "Canada"): ("High Commission of Canada, Hong Kong", "12/F, Tower One, Exchange Square, 8 Connaught Place, Central, Hong Kong", "+852 3719 4700", "hongkong.gc.ca", "Apply online at ircc.canada.ca. The Canadian Consulate-General in Hong Kong handles consular matters."),
    ("Hungary", "Canada"): ("Embassy of Canada, Budapest", "Ganz utca 12-14, 1027 Budapest, Hungary", "+36 1 392 3360", "hungary.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Budapest handles consular matters."),
    ("Ireland", "Canada"): ("Embassy of Canada, Dublin", "7-8 Wilton Terrace, Dublin 2, Ireland", "+353 1 234 4000", "ireland.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Irish applicants."),
    ("Italy", "Canada"): ("Embassy of Canada, Rome", "Via Zara 30, 00198 Rome, Italy", "+39 06 854 442 911", "italy.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Italian applicants."),
    ("Japan", "Canada"): ("Embassy of Canada, Tokyo", "7-3-38 Akasaka, Minato-ku, Tokyo 107-8503, Japan", "+81 3 5412 6200", "japan.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Japanese applicants."),
    ("Latvia", "Canada"): ("Embassy of Canada, Riga", "Baznīcas iela 20/22, 1010 Riga, Latvia", "+371 6781 3945", "latvia.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Riga handles consular matters."),
    ("Lithuania", "Canada"): ("Embassy of Canada, Vilnius", "Jogailos 4, 01116 Vilnius, Lithuania", "+370 5 249 0950", "lithuania.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Vilnius handles consular matters."),
    ("Luxembourg", "Canada"): ("Embassy of Canada, Brussels (covers Luxembourg)", "Avenue de Tervuren 2, 1040 Brussels, Belgium", "+32 2 741 0611", "belgium.gc.ca", "Apply online at ircc.canada.ca. Luxembourg applicants are served by the Canadian Embassy in Brussels."),
    ("Mainland China", "Canada"): ("Embassy of Canada, Beijing", "19 Dongzhimenwai Dajie, Chaoyang District, Beijing 100600, China", "+86 10 5139 4000", "china.gc.ca", "Apply online at ircc.canada.ca or through VFS Global. Also contact Consulate-General in Shanghai, Guangzhou, or Chongqing."),
    ("Netherlands", "Canada"): ("Embassy of Canada, The Hague", "Sophialaan 7, 2514 JP The Hague, Netherlands", "+31 70 311 1600", "netherlands.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in The Hague handles consular matters."),
    ("New Zealand", "Canada"): ("High Commission of Canada, Wellington", "Level 11, 125 The Terrace, Wellington 6011, New Zealand", "+64 4 473 9577", "newzealand.gc.ca", "Apply online at ircc.canada.ca. The High Commission handles consular matters for New Zealand applicants."),
    ("Norway", "Canada"): ("Embassy of Canada, Oslo", "Wergelandsveien 7, 0244 Oslo, Norway", "+47 22 99 53 00", "norway.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Oslo handles consular matters."),
    ("Poland", "Canada"): ("Embassy of Canada, Warsaw", "Ulica Jana Matejki 1/5, 00-481 Warsaw, Poland", "+48 22 584 3100", "poland.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Polish applicants."),
    ("Portugal", "Canada"): ("Embassy of Canada, Lisbon", "Av. da Liberdade 198-200, 4th Floor, 1269-121 Lisbon, Portugal", "+351 21 316 4600", "portugal.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Portuguese applicants."),
    ("Slovakia", "Canada"): ("Embassy of Canada, Bratislava", "Carlton Savoy Building, Mostová 2, 811 02 Bratislava, Slovakia", "+421 2 5920 4031", "slovakia.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Bratislava handles consular matters."),
    ("Slovenia", "Canada"): ("Embassy of Canada, Ljubljana", "Trg republike 3, 1000 Ljubljana, Slovenia", "+386 1 252 4444", "slovenia.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Ljubljana handles consular matters."),
    ("South Korea", "Canada"): ("Embassy of Canada, Seoul", "21F Jeongdong Building, 21-15 Jeongdong-gil, Jung-gu, Seoul 04518", "+82 2 3783 6000", "southkorea.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for South Korean applicants."),
    ("Spain", "Canada"): ("Embassy of Canada, Madrid", "Torre Espacio, Paseo de la Castellana 259D, 28046 Madrid, Spain", "+34 91 382 8400", "spain.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Spanish applicants."),
    ("Sweden", "Canada"): ("Embassy of Canada, Stockholm", "Klarabergsviadukten 63, 111 64 Stockholm, Sweden", "+46 8 453 3000", "sweden.gc.ca", "Apply online at ircc.canada.ca. The Embassy handles consular matters for Swedish applicants."),
    ("Switzerland", "Canada"): ("Embassy of Canada, Bern", "Kirchenfeldstrasse 88, 3005 Bern, Switzerland", "+41 31 357 3200", "switzerland.gc.ca", "Apply online at ircc.canada.ca. The Canadian Embassy in Bern handles consular matters."),
    ("Taiwan", "Canada"): ("Canadian Trade Office in Taipei", "6F, 365 Fu Hsing North Road, Taipei 10546", "+886 2 2544 3000", "taiwan.gc.ca", "Apply online at ircc.canada.ca. The Canadian Trade Office in Taipei provides consular services."),
    ("United Kingdom", "Canada"): ("High Commission of Canada, London", "Canada House, Trafalgar Square, London SW1Y 5BJ, United Kingdom", "+44 20 7004 6000", "unitedkingdom.gc.ca", "Apply online at ircc.canada.ca. The High Commission handles consular matters for UK applicants."),
    ("USA", "Canada"): ("Embassy of Canada, Washington D.C.", "501 Pennsylvania Avenue NW, Washington, DC 20001, USA", "+1 202 682 1740", "usa.gc.ca", "Apply online at ircc.canada.ca. Also contact Consulate-General in New York, Los Angeles, Chicago, Atlanta, Seattle, Minneapolis, Dallas, or San Francisco."),

    # UK as destination
    ("Australia", "United Kingdom"): ("British High Commission, Canberra", "Commonwealth Avenue, Yarralumla, ACT 2600, Australia", "+61 2 6270 6666", "gov.uk/world/australia", "Apply online at gov.uk/apply-to-come-to-the-uk. The British High Commission handles consular matters for Australian applicants."),
    ("Austria", "United Kingdom"): ("British Embassy, Vienna", "Jaurèsgasse 12, 1030 Vienna, Austria", "+43 1 716 130", "gov.uk/world/austria", "Apply online at gov.uk/apply-to-come-to-the-uk. The British Embassy in Vienna handles consular matters."),
    ("Canada", "United Kingdom"): ("British High Commission, Ottawa", "80 Elgin Street, Ottawa, ON K1P 5K7, Canada", "+1 613 237 1530", "gov.uk/world/canada", "Apply online at gov.uk/apply-to-come-to-the-uk. The High Commission handles consular matters for Canadian applicants."),
    ("Germany", "United Kingdom"): ("British Embassy, Berlin", "Wilhelmstrasse 70-71, 10117 Berlin, Germany", "+49 30 204 570", "gov.uk/world/germany", "Apply online at gov.uk/apply-to-come-to-the-uk. The British Embassy in Berlin handles consular matters."),
    ("Hong Kong", "United Kingdom"): ("British Consulate-General, Hong Kong", "1 Supreme Court Road, Admiralty, Hong Kong", "+852 2901 3000", "gov.uk/world/hong-kong", "Apply online at gov.uk/apply-to-come-to-the-uk. The British Consulate-General handles consular matters for Hong Kong applicants."),
    ("Japan", "United Kingdom"): ("British Embassy, Tokyo", "1 Ichiban-cho, Chiyoda-ku, Tokyo 102-8381, Japan", "+81 3 5211 1100", "gov.uk/world/japan", "Apply online at gov.uk/apply-to-come-to-the-uk. The British Embassy in Tokyo handles consular matters."),
    ("Mainland China", "United Kingdom"): ("British Embassy, Beijing", "11 Guang Hua Lu, Jian Guo Men Wai, Beijing 100600, China", "+86 10 5192 4000", "gov.uk/world/china", "Apply online at gov.uk/apply-to-come-to-the-uk. Also contact British Consulate-General in Shanghai, Guangzhou, Chongqing, or Wuhan."),
    ("New Zealand", "United Kingdom"): ("British High Commission, Wellington", "44 Hill Street, Thorndon, Wellington 6011, New Zealand", "+64 4 924 2888", "gov.uk/world/new-zealand", "Apply online at gov.uk/apply-to-come-to-the-uk. The High Commission handles consular matters for New Zealand applicants."),
    ("South Korea", "United Kingdom"): ("British Embassy, Seoul", "Taepyeongno 40, 4 Jeong-dong, Jung-gu, Seoul 04519", "+82 2 3210 5500", "gov.uk/world/south-korea", "Apply online at gov.uk/apply-to-come-to-the-uk. The British Embassy in Seoul handles consular matters."),
    ("Taiwan", "United Kingdom"): ("British Office, Taipei", "26F, President International Tower, 9-11 Songgao Road, Xinyi District, Taipei 11073", "+886 2 8758 2088", "gov.uk/world/taiwan", "Apply online at gov.uk/apply-to-come-to-the-uk. The British Office in Taipei provides consular services for Taiwanese applicants."),
    ("USA", "United Kingdom"): ("British Embassy, Washington D.C.", "3100 Massachusetts Avenue NW, Washington, DC 20008, USA", "+1 202 588 6500", "gov.uk/world/usa", "Apply online at gov.uk/apply-to-come-to-the-uk. Also contact British Consulate-General in New York, Los Angeles, Chicago, Atlanta, Boston, Houston, Miami, or San Francisco."),

    # Ireland as destination
    ("Argentina", "Ireland"): ("Embassy of Ireland, Buenos Aires", "Av. del Libertador 1068, 6th Floor, Recoleta, C1112ABN Buenos Aires", "+54 11 4808 5700", "ireland.ie/argentina", "Apply via Visa Online (visaonline.garda.ie). The Irish Embassy in Buenos Aires handles consular matters."),
    ("Australia", "Ireland"): ("Embassy of Ireland, Canberra", "20 Arkana Street, Yarralumla ACT 2600, Australia", "+61 2 6214 0000", "ireland.ie/australia", "Apply via Visa Online (visaonline.garda.ie). The Irish Embassy in Canberra handles consular matters."),
    ("Canada", "Ireland"): ("Embassy of Ireland, Ottawa", "130 Albert Street, Suite 1105, Ottawa, ON K1P 5G4, Canada", "+1 613 233 6281", "ireland.ie/canada", "Apply via Visa Online. The Irish Embassy in Ottawa handles consular matters for Canadian applicants."),
    ("Chile", "Ireland"): ("Embassy of Ireland, Santiago", "Isidora Goyenechea 3162, Piso 4, Las Condes, Santiago, Chile", "+56 2 2245 6978", "ireland.ie/chile", "Apply via Visa Online. The Irish Embassy in Santiago handles consular matters for Chilean applicants."),
    ("Hong Kong", "Ireland"): ("Consulate-General of Ireland, Hong Kong", "GPO Box 4534, Central, Hong Kong", "+852 2527 4897", "ireland.ie/hong-kong", "Apply via Visa Online. The Irish Consulate-General in Hong Kong handles consular matters."),
    ("Japan", "Ireland"): ("Embassy of Ireland, Tokyo", "Ireland House, 2-10-7 Kojimachi, Chiyoda-ku, Tokyo 102-0083, Japan", "+81 3 3263 0695", "ireland.ie/japan", "Apply via Visa Online (visaonline.garda.ie). The Irish Embassy in Tokyo handles consular matters."),
    ("New Zealand", "Ireland"): ("Embassy of Ireland, Wellington", "Level 11, Sovereign Assurance House, 34-42 Manners Street, Wellington 6011", "+64 4 977 2252", "ireland.ie/new-zealand", "Apply via Visa Online. The Irish Embassy in Wellington handles consular matters for New Zealand applicants."),
    ("South Korea", "Ireland"): ("Embassy of Ireland, Seoul", "13F Leema Building, 42 Jongno, Jongno-gu, Seoul 03143", "+82 2 721 7200", "ireland.ie/south-korea", "Apply via Visa Online. The Irish Embassy in Seoul handles consular matters for Korean applicants."),
    ("Taiwan", "Ireland"): ("Ireland Trade & Cultural Office, Taipei", "8F, No. 139, Minsheng East Road, Sec. 3, Zhongshan District, Taipei 10596", "+886 2 2508 1600", "ireland.ie/taiwan", "Apply via Visa Online. The Ireland Trade & Cultural Office in Taipei provides consular services."),
    ("USA", "Ireland"): ("Embassy of Ireland, Washington D.C.", "2234 Massachusetts Avenue NW, Washington, DC 20008, USA", "+1 202 462 3939", "ireland.ie/usa", "Apply via Visa Online. Also contact Irish Consulate-General in New York, Boston, Chicago, or San Francisco."),

    # Austria as destination
    ("Argentina", "Austria"): ("Austrian Embassy, Buenos Aires", "Calle French 3671, 1425 Buenos Aires, Argentina", "+54 11 4809 5800", "bmeia.gv.at/oeb-buenos-aires", "Apply via VFS Global or the Austrian Embassy in Buenos Aires. Long-stay WHV requires advance application."),
    ("Australia", "Austria"): ("Austrian Embassy, Canberra", "12 Talbot Street, Forrest ACT 2603, Australia", "+61 2 6295 1533", "bmeia.gv.at/oeb-canberra", "Apply via VFS Global in Sydney, Canberra, Melbourne, Brisbane, Adelaide, or Perth. Appointment required."),
    ("Canada", "Austria"): ("Austrian Embassy, Ottawa", "445 Wilbrod Street, Ottawa, ON K1N 6M7, Canada", "+1 613 789 1444", "bmeia.gv.at/oeb-ottawa", "Apply via VFS Global in Canada. The Austrian Embassy in Ottawa handles consular matters."),
    ("Chile", "Austria"): ("Austrian Embassy, Santiago", "Barros Errázuriz 1968, Piso 3, Providencia, Santiago, Chile", "+56 2 2233 4284", "bmeia.gv.at/oeb-santiago", "Apply via the Austrian Embassy or VFS Global in Santiago. Long-stay WHV requires advance application."),
    ("Germany", "Austria"): ("Austrian Embassy, Berlin", "Stauffenbergstrasse 1, 10785 Berlin, Germany", "+49 30 202 870", "bmeia.gv.at/oeb-berlin", "Austrian visas for German citizens: EU freedom of movement applies. Contact for long-stay work permits."),
    ("Hong Kong", "Austria"): ("Austrian Consulate-General, Hong Kong", "8/F, Generali Tower, 8 Queen's Road East, Wanchai, Hong Kong", "+852 2522 0246", "bmeia.gv.at/oek-hong-kong", "Apply via the Austrian Consulate-General in Hong Kong. WHV requires appointment and advance application."),
    ("Japan", "Austria"): ("Austrian Embassy, Tokyo", "1-1-20 Moto-Azabu, Minato-ku, Tokyo 106-0046, Japan", "+81 3 3451 8281", "bmeia.gv.at/oeb-tokio", "Apply via the Austrian Embassy in Tokyo. WHV requires advance application and appointment."),
    ("Mainland China", "Austria"): ("Austrian Embassy, Beijing", "Jingguang Centre, Unit 2502, Hu Jia Lou, Chaoyang District, Beijing 100020", "+86 10 6532 2061", "bmeia.gv.at/oeb-peking", "Apply via the Austrian Embassy in Beijing or Consulate in Shanghai. WHV requires advance application."),
    ("New Zealand", "Austria"): ("Austrian Embassy, Canberra (covers NZ)", "12 Talbot Street, Forrest ACT 2603, Australia", "+61 2 6295 1533", "bmeia.gv.at/oeb-canberra", "Apply via VFS Global in Auckland or Wellington. New Zealand WHV applicants submit applications through VFS Global."),
    ("South Korea", "Austria"): ("Austrian Embassy, Seoul", "Dongbinggo-ro 11-gil 7, Yongsan-gu, Seoul 04337", "+82 2 732 9071", "bmeia.gv.at/oeb-seoul", "Apply via the Austrian Embassy in Seoul. WHV requires advance application and appointment."),
    ("Taiwan", "Austria"): ("Austrian Trade Commission, Taipei", "9/F, 99 Jhongching South Road, Sec. 1, Taipei 10845", "+886 2 2381 0367", "wko.at/taiwan", "Apply via VFS Global or the Austrian Trade Commission in Taipei. WHV requires advance application."),
    ("United Kingdom", "Austria"): ("Austrian Embassy, London", "18 Belgrave Mews West, London SW1X 8HU, United Kingdom", "+44 20 7235 3731", "bmeia.gv.at/oeb-london", "Apply via VFS Global or the Austrian Embassy in London. WHV requires advance application and appointment."),
    ("USA", "Austria"): ("Austrian Embassy, Washington D.C.", "3524 International Court NW, Washington, DC 20008, USA", "+1 202 895 6700", "bmeia.gv.at/oeb-washington", "Apply via the Austrian Embassy in Washington D.C. or Consulate-General in New York, Chicago, or Los Angeles."),

    # Taiwan as destination
    ("Australia", "Taiwan"): ("Taipei Economic and Cultural Office, Canberra", "Unit 8, 40 Blackall Street, Barton ACT 2600, Australia", "+61 2 6120 2000", "roc-taiwan.org/au_en", "Apply at the TECO office nearest to you. Branch offices in Sydney, Melbourne, and Brisbane also handle WHV applications."),
    ("Austria", "Taiwan"): ("Taipei Economic and Cultural Office, Vienna", "Praterstrasse 31/12, 1020 Vienna, Austria", "+43 1 212 4720", "roc-taiwan.org/at_en", "Apply at the TECO in Vienna. WHV requires in-person application with all required documents."),
    ("Belgium", "Taiwan"): ("Taipei Representative Office, Brussels", "Rue Guillaume Stocq 2, 1050 Brussels, Belgium", "+32 2 511 0687", "roc-taiwan.org/be_en", "Apply at the Taipei Representative Office in Brussels. WHV requires in-person application."),
    ("Canada", "Taiwan"): ("Taipei Economic and Cultural Office, Ottawa", "45 O'Connor Street, Suite 1960, Ottawa, ON K1P 1A4, Canada", "+1 613 231 5080", "roc-taiwan.org/ca_en", "Apply at the TECO nearest to you. Offices in Toronto, Vancouver, and Calgary also handle WHV applications."),
    ("Czech Republic", "Taiwan"): ("Taipei Economic and Cultural Office, Prague", "Korunní 110/2588, 101 00 Prague 10, Czech Republic", "+420 257 531 798", "roc-taiwan.org/cz_en", "Apply at the TECO in Prague. WHV requires in-person application with all required documents."),
    ("France", "Taiwan"): ("Bureau de Représentation de Taipei en France", "78 Rue de l'Université, 75007 Paris, France", "+33 1 4439 8830", "roc-taiwan.org/fr_en", "Apply at the Taipei Representative Office in Paris. WHV requires in-person application."),
    ("Germany", "Taiwan"): ("Taipei Representative Office, Berlin", "Markgrafenstrasse 35, 10117 Berlin, Germany", "+49 30 203 610", "roc-taiwan.org/de_en", "Apply at the Taipei Representative Office in Berlin or branch offices in Frankfurt, Hamburg, or Munich."),
    ("Hong Kong", "Taiwan"): ("Taipei Economic and Cultural Office, Hong Kong", "4/F, Silvercord Tower 1, 30 Canton Road, Tsim Sha Tsui, Hong Kong", "+852 2525 8315", "roc-taiwan.org/hk_en", "Apply at the TECO in Hong Kong. WHV requires in-person application with all required documents."),
    ("Hungary", "Taiwan"): ("Taipei Representative Office, Budapest", "Bajcsy-Zsilinszky út 12, 2nd Floor, 1051 Budapest, Hungary", "+36 1 266 2884", "roc-taiwan.org/hu_en", "Apply at the Taipei Representative Office in Budapest. WHV requires in-person application."),
    ("Ireland", "Taiwan"): ("Taipei Representative Office, Dublin", "8 Lower Fitzwilliam Street, Dublin 2, Ireland", "+353 1 678 5413", "roc-taiwan.org/ie_en", "Apply at the Taipei Representative Office in Dublin. WHV requires in-person application with all required documents."),
    ("Japan", "Taiwan"): ("Taiwan-Japan Relations Association (MOFA)", "20F, Shin-Kokusai Building, 3-4-1 Marunouchi, Chiyoda-ku, Tokyo 100-0005", "+81 3 3218 4531", "koryu.or.jp", "Apply through the Interchange Association Japan in Taipei. WHV requires advance in-person application."),
    ("Mainland China", "Taiwan"): ("Straits Exchange Foundation (SEF)", "No. 65, Hangzhou South Road, Sec. 1, Zhongzheng District, Taipei 10065", "+886 2 2396 5000", "sef.org.tw", "Cross-strait travel arrangements apply. Contact the SEF for travel and residency enquiries between Mainland China and Taiwan."),
    ("Netherlands", "Taiwan"): ("Netherlands Office, Taipei", "5F, No. 133 Minsheng East Road, Sec. 3, Zhongshan District, Taipei 10544", "+886 2 2713 5110", "roc-taiwan.org/nl_en", "Apply at the TECO or Netherlands Office in Taipei. WHV requires in-person application."),
    ("New Zealand", "Taiwan"): ("New Zealand Commerce & Industry Office, Taipei", "25/F, Taipei 101 Tower, No. 7, Sec. 5, Xinyi Road, Taipei 11049", "+886 2 2720 5228", "roc-taiwan.org/nz_en", "Apply at the TECO in Wellington or Auckland. The NZ Commerce & Industry Office in Taipei handles consular matters."),
    ("Poland", "Taiwan"): ("Taipei Representative Office, Warsaw", "Szucha Avenue 17/2, 00-580 Warsaw, Poland", "+48 22 625 2483", "roc-taiwan.org/pl_en", "Apply at the Taipei Representative Office in Warsaw. WHV requires in-person application."),
    ("Slovakia", "Taiwan"): ("Taipei Economic and Cultural Office, Bratislava", "Dunajská 4, 811 08 Bratislava, Slovakia", "+421 2 5296 2871", "roc-taiwan.org/sk_en", "Apply at the TECO in Bratislava. WHV requires in-person application with all required documents."),
    ("South Korea", "Taiwan"): ("Taipei Mission in Korea", "6F, Gwanghwamun Building, 149 Sejong-daero, Jongno-gu, Seoul 03186", "+82 2 399 2767", "roc-taiwan.org/kr_en", "Apply at the Taipei Mission in Seoul. WHV requires in-person application with all required documents."),
    ("United Kingdom", "Taiwan"): ("Taipei Representative Office, London", "50 Grosvenor Gardens, London SW1W 0EB, United Kingdom", "+44 20 7881 2650", "roc-taiwan.org/gb_en", "Apply at the Taipei Representative Office in London. WHV requires in-person application with all required documents."),
    ("USA", "Taiwan"): ("Taipei Economic and Cultural Representative Office (TECRO), Washington D.C.", "4201 Wisconsin Avenue NW, Washington, DC 20016, USA", "+1 202 895 1800", "roc-taiwan.org/us_en", "Apply at the TECRO or nearest TECO office. Offices in New York, Los Angeles, Chicago, Houston, San Francisco, Boston, Guam, Atlanta, and Kansas City."),

    # Hong Kong as destination
    ("Australia", "Hong Kong"): ("Hong Kong Economic and Trade Office, Sydney", "Level 19, 56 Pitt Street, Sydney NSW 2000, Australia", "+61 2 9251 9077", "hongkong.org.au", "Hong Kong operates an open visa policy for many nationalities. Visit immd.gov.hk for working visa requirements."),
    ("Austria", "Hong Kong"): ("Hong Kong Economic and Trade Office, Brussels", "Avenue des Arts 58, 1000 Brussels, Belgium", "+32 2 774 0200", "hketob.be", "Apply at the Hong Kong Immigration Dept (immd.gov.hk). Austrian applicants can also contact the HKETO in Brussels."),
    ("Canada", "Hong Kong"): ("Hong Kong Economic and Trade Office, Toronto", "Suite 3550, 145 King Street West, Toronto, ON M5H 1J8, Canada", "+1 416 924 5544", "hketotoronto.com", "Apply at immd.gov.hk. Canadian applicants can contact the HKETO in Toronto or Vancouver for consular support."),
    ("France", "Hong Kong"): ("Hong Kong Economic and Trade Office, Brussels", "Avenue des Arts 58, 1000 Brussels, Belgium", "+32 2 774 0200", "hketob.be", "Apply at immd.gov.hk. French applicants can contact the HKETO in Brussels for consular support."),
    ("Germany", "Hong Kong"): ("Hong Kong Economic and Trade Office, Berlin", "Bleibtreustrasse 17, 10623 Berlin, Germany", "+49 30 206 7280", "hketob.de", "Apply at immd.gov.hk. German applicants can contact the HKETO in Berlin for consular support."),
    ("Hungary", "Hong Kong"): ("Hong Kong Immigration Dept (via HKETO Brussels)", "Avenue des Arts 58, 1000 Brussels, Belgium", "+32 2 774 0200", "immd.gov.hk", "Apply at immd.gov.hk. Hungarian applicants contact the HKETO in Brussels for working visa enquiries."),
    ("Ireland", "Hong Kong"): ("Hong Kong Economic and Trade Office, London", "6 Grafton Street, London W1S 4EQ, United Kingdom", "+44 20 3701 7300", "hketolondon.gov.hk", "Apply at immd.gov.hk. Irish applicants can contact the HKETO in London for consular support."),
    ("Italy", "Hong Kong"): ("Hong Kong Economic and Trade Office, Rome", "Via Barberini 3, 00187 Rome, Italy", "+39 06 420 3840", "italy.gov.hk", "Apply at immd.gov.hk. Italian applicants can contact the HKETO in Rome for working visa enquiries."),
    ("Japan", "Hong Kong"): ("Hong Kong Economic and Trade Office, Tokyo", "Toranomon Kotohira Tower, 2-8-1 Toranomon, Minato-ku, Tokyo 105-0001", "+81 3 3556 8981", "hketo.jp", "Apply at immd.gov.hk. Japanese applicants contact the HKETO in Tokyo for consular support."),
    ("Mainland China", "Hong Kong"): ("Immigration Department, Hong Kong SAR", "2/F, Immigration Tower, 7 Gloucester Road, Wan Chai, Hong Kong", "+852 2824 6111", "immd.gov.hk", "Mainland China citizens require a Home Return Permit (回乡证) or other permit to work in Hong Kong. Contact the Immigration Dept."),
    ("Netherlands", "Hong Kong"): ("Hong Kong Economic and Trade Office, Brussels", "Avenue des Arts 58, 1000 Brussels, Belgium", "+32 2 774 0200", "hketob.be", "Apply at immd.gov.hk. Dutch applicants contact the HKETO in Brussels for working visa enquiries."),
    ("New Zealand", "Hong Kong"): ("Hong Kong Economic and Trade Office, Sydney", "Level 19, 56 Pitt Street, Sydney NSW 2000, Australia", "+61 2 9251 9077", "hongkong.org.au", "Apply at immd.gov.hk. New Zealand applicants can contact the HKETO in Sydney for consular support."),
    ("South Korea", "Hong Kong"): ("Hong Kong Economic and Trade Office, Seoul", "19F, Trade Tower, 511 Yeongdong-daero, Gangnam-gu, Seoul 06164", "+82 2 3789 6700", "hketo.kr", "Apply at immd.gov.hk. Korean applicants can contact the HKETO in Seoul for working visa enquiries."),
    ("Sweden", "Hong Kong"): ("Hong Kong Economic and Trade Office, London", "6 Grafton Street, London W1S 4EQ, United Kingdom", "+44 20 3701 7300", "hketolondon.gov.hk", "Apply at immd.gov.hk. Swedish applicants can contact the HKETO in London for working visa enquiries."),
    ("Taiwan", "Hong Kong"): ("Taipei Economic and Cultural Office, Hong Kong", "4/F, Silvercord Tower 1, 30 Canton Road, Tsim Sha Tsui, Hong Kong", "+852 2525 8315", "roc-taiwan.org/hk_en", "Apply at immd.gov.hk. Taiwanese citizens in Hong Kong can contact the TECO for travel document assistance."),
    ("United Kingdom", "Hong Kong"): ("Hong Kong Economic and Trade Office, London", "6 Grafton Street, London W1S 4EQ, United Kingdom", "+44 20 3701 7300", "hketolondon.gov.hk", "Apply at immd.gov.hk. UK applicants contact the HKETO in London for working visa enquiries."),
    ("USA", "Hong Kong"): ("Hong Kong Economic and Trade Office, San Francisco", "130 Montgomery Street, Suite 1600, San Francisco, CA 94104, USA", "+1 415 835 9300", "hketosfo.com", "Apply at immd.gov.hk. US applicants contact the HKETO in Washington D.C., New York, or San Francisco."),
}

HTML_TEMPLATE = '''            <!-- Authority Contact -->
            <div class="row mt-4">
                <div class="col-12">
                    <div class="embassy-card p-4 rounded bg-light border">
                        <h5 class="mb-3"><i class="fa fa-building-columns mr-3 text-primary"></i>{name}</h5>
                        <p class="mb-2"><strong>Address:</strong> {address}</p>
                        <p class="mb-2"><strong>Phone:</strong> {phone}</p>
                        <p class="mb-2"><strong>Website:</strong> <a href="https://{website}" target="_blank">{website}</a></p>
                        <p class="small mb-0 text-muted"><strong>Application Note:</strong> {note}</p>
                    </div>
                </div>
            </div>'''

OLD_BLOCK_PATTERN = re.compile(
    r'            <!-- Authority Contact -->.*?</div>\s*</div>\s*</div>',
    re.DOTALL
)

def parse_filename(fname):
    # e.g. Argentina-to-Australia.html
    name = fname.replace('.html', '')
    parts = name.split('-to-')
    if len(parts) == 2:
        origin = parts[0].replace('-', ' ')
        dest = parts[1].replace('-', ' ')
        return origin, dest
    return None, None

updated = 0
skipped = 0
no_data = []

for fname in os.listdir(BASE):
    if not fname.endswith('.html'):
        continue
    origin, dest = parse_filename(fname)
    if not origin or not dest:
        continue

    key = (origin, dest)
    if key not in EMBASSIES:
        no_data.append(fname)
        skipped += 1
        continue

    name, address, phone, website, note = EMBASSIES[key]
    new_block = HTML_TEMPLATE.format(name=name, address=address, phone=phone, website=website, note=note)

    fpath = os.path.join(BASE, fname)
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()

    new_content = OLD_BLOCK_PATTERN.sub(new_block, content)
    if new_content != content:
        with open(fpath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        updated += 1
    else:
        skipped += 1

print(f"Updated: {updated}")
print(f"Skipped (no data or no match): {skipped}")
print(f"Files without embassy data: {len(no_data)}")
if no_data:
    print("No data for:")
    for f in sorted(no_data):
        print(" ", f)
